site_name: Curriculum
theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-3 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
      primary: teal
